"use client";
import { useMemo, useState } from "react";
type Item={id:number;partNumber:string;name:string;category:string;qtyNeeded:number;qtyOnHand:number;unitCost:number|null;unit:string;purchaseUrl:string};
const number=new Intl.NumberFormat("en-US",{maximumFractionDigits:3});
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
export default function BuildPlanner({items}:{items:Item[]}){
 const [open,setOpen]=useState(false),[input,setInput]=useState("1");const chairs=Math.max(0,Math.floor(Number(input)||0));
 const rows=useMemo(()=>items.filter(i=>i.qtyNeeded>0&&i.category.toLowerCase()!=="battery"&&!i.name.toLowerCase().includes("battery")).map(i=>{const required=chairs*i.qtyNeeded,toBuy=Math.max(0,required-i.qtyOnHand),leftover=i.qtyOnHand+toBuy-required;return{...i,required,toBuy,leftover,extraChairs:Math.floor(leftover/i.qtyNeeded)}}).sort((a,b)=>Number(b.toBuy>0)-Number(a.toBuy>0)||a.name.localeCompare(b.name)),[items,chairs]);
 const buys=rows.filter(r=>r.toBuy>0),knownCost=buys.reduce((s,r)=>s+r.toBuy*(r.unitCost||0),0);
 return <><button className="planner-tab" onClick={()=>setOpen(true)}>Build Planner</button>{open&&<div className="planner-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><aside className="planner-drawer" aria-label="Chair build planner"><button className="close" onClick={()=>setOpen(false)}>×</button><p className="eyebrow">PURCHASING CALCULATOR</p><h2>Plan your next chairs</h2><p className="muted">Enter your target and see exactly what must be purchased, plus the usable stock remaining afterward.</p><label className="chair-target">Chairs needed<input min="0" step="1" type="number" value={input} onChange={e=>setInput(e.target.value)}/></label><div className="planner-summary"><article><span>Target</span><strong>{chairs}</strong><small>chairs</small></article><article><span>Parts to buy</span><strong>{buys.length}</strong><small>purchase lines</small></article><article><span>Known cost</span><strong>{money.format(knownCost)}</strong><small>excludes blank prices</small></article></div><p className="planner-note">Batteries are excluded, matching the New Chair button. Purchase quantities are exact BOM units and do not account for supplier package sizes.</p><div className="planner-table-wrap"><table className="planner-table"><thead><tr><th>Part</th><th>Needed</th><th>On hand</th><th>Buy</th><th>Left over</th><th>Extra chairs from this part</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={r.toBuy>0?"needs-buy":""}><td><strong>{r.name}</strong><small>{r.partNumber||"No part number"}</small></td><td>{number.format(r.required)} {r.unit}</td><td>{number.format(r.qtyOnHand)} {r.unit}</td><td><b>{number.format(r.toBuy)} {r.unit}</b>{r.toBuy>0&&r.purchaseUrl&&<a href={r.purchaseUrl} target="_blank" rel="noreferrer">Buy ↗</a>}</td><td>{number.format(r.leftover)} {r.unit}</td><td><strong>{number.format(r.extraChairs)}</strong> chairs</td></tr>)}</tbody></table></div></aside></div>}</>;
}
