"use client";
import {useEffect,useMemo,useState} from "react";
type Item={id:number;partNumber:string;name:string;category:string;qtyNeeded:number;qtyOnHand:number;unit:string};type Chair={id:number;name:string;chairColor:string;remoteColor:string;notes:string};type Part={chairId:number;itemId:number;quantity:number};type Asset={id:number;chairId:number;type:string;partId:string;status:string;updatedAt:string};type Appearance={chairId:number;chairColor:string;remoteColor:string;wheelPosition:"F"|"M"};
export default function ChairTracker({items,onInventoryChange}:{items:Item[];onInventoryChange:()=>Promise<void>}){
 const[chairs,setChairs]=useState<Chair[]>([]),[parts,setParts]=useState<Part[]>([]),[assets,setAssets]=useState<Asset[]>([]),[appearances,setAppearances]=useState<Appearance[]>([]),[active,setActive]=useState<number|null>(null),[message,setMessage]=useState("");
 const bom=useMemo(()=>items.filter(i=>i.qtyNeeded>0&&i.category.toLowerCase()!=="battery"&&!i.name.toLowerCase().includes("battery")),[items]);
 async function load(){const[r,m]=await Promise.all([fetch("/api/chairs"),fetch("/api/chair-appearance")]),d=await r.json(),meta=await m.json();setChairs(d.chairs||[]);setParts(d.parts||[]);setAssets(d.assets||[]);setAppearances(meta||[])}useEffect(()=>{load()},[]);
 const complete=(id:number)=>assets.filter(a=>a.chairId===id&&a.status==="Installed").length>=8||(bom.length>0&&bom.every(i=>(parts.find(p=>p.chairId===id&&p.itemId===i.id)?.quantity||0)>=i.qtyNeeded));
 const look=(c:Chair)=>appearances.find(a=>a.chairId===c.id)||{chairId:c.id,chairColor:c.chairColor||"#3274bb",remoteColor:c.remoteColor||"#14161e",wheelPosition:"M" as const};
 async function saveLook(id:number,next:Appearance){setAppearances(x=>[...x.filter(a=>a.chairId!==id),next]);await fetch(`/api/chairs/${id}/appearance`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)})}
 async function add(){const name=prompt("Enter the chair ID (example: CHAIR-003)");if(!name)return;const r=await fetch("/api/chairs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})}),d=await r.json();if(!r.ok)return setMessage(d.error);await load();setActive(d.id)}
 async function change(item:Item,quantity:number){if(active===null)return;const r=await fetch(`/api/chairs/${active}/parts/${item.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({quantity,status:"Installed"})}),d=await r.json();if(!r.ok)return setMessage(d.error);setMessage("Chair and loose inventory updated together.");await Promise.all([load(),onInventoryChange()])}
 async function remove(c:Chair){if(!confirm(`Delete ${c.name}? Installed BOM parts will return to inventory.`))return;await fetch(`/api/chairs/${c.id}`,{method:"DELETE"});setActive(null);await Promise.all([load(),onInventoryChange()])}
 const selected=chairs.find(c=>c.id===active),installed=selected?parts.filter(p=>p.chairId===selected.id):[],tracked=selected?assets.filter(a=>a.chairId===selected.id):[];
 if(selected){const a=look(selected);return <section className="chair-workspace"><button className="ghost" onClick={()=>setActive(null)}>← All chairs</button><div className="chair-detail-head"><div><p className="eyebrow">CHAIR BUILD RECORD</p><h2>{selected.name}</h2><span className={`chair-state ${complete(selected.id)?"complete":"progress"}`}>{complete(selected.id)?"Fully built":"In progress"}</span></div><div className="appearance-editor"><label>Chair color<input type="color" value={a.chairColor} onChange={e=>saveLook(selected.id,{...a,chairColor:e.target.value})}/></label><label>Remote color<input type="color" value={a.remoteColor} onChange={e=>saveLook(selected.id,{...a,remoteColor:e.target.value})}/></label><label>Wheel<select value={a.wheelPosition} onChange={e=>saveLook(selected.id,{...a,wheelPosition:e.target.value as "F"|"M"})}><option value="F">F — Front Wheel</option><option value="M">M — Mid Wheel</option></select></label><button className="delete-item" onClick={()=>remove(selected)}>Delete chair</button></div></div>{message&&<p className="tracker-message">{message}</p>}{tracked.length>0&&<div className="tracked-assets"><h3>Installed identifiers</h3><div>{tracked.map(x=><article key={x.id}><span>{x.type}</span><strong>{x.partId}</strong><small>{x.status} · {new Date(x.updatedAt).toLocaleDateString()}</small></article>)}</div><p>Imported historical records did not reduce today’s loose inventory.</p></div>}<div className="table-wrap"><table><thead><tr><th>BOM part</th><th>Required</th><th>Installed</th><th>Loose inventory</th><th>Move parts</th><th>Status</th></tr></thead><tbody>{bom.map(i=>{const qty=installed.find(p=>p.itemId===i.id)?.quantity||0,done=qty>=i.qtyNeeded;return <tr key={i.id}><td><strong>{i.name}</strong><small>{i.partNumber||"No part number"}</small></td><td>{i.qtyNeeded} {i.unit}</td><td><b>{qty}</b> {i.unit}</td><td>{i.qtyOnHand} {i.unit}</td><td><div className="quantity-actions"><button disabled={qty<=0} onClick={()=>change(i,Math.max(0,qty-1))}>− Return</button><button disabled={i.qtyOnHand<=0} onClick={()=>change(i,qty+1)}>+ Install</button></div></td><td><span className={`badge ${done?"ready":"low"}`}>{done?"Complete":"Needed"}</span></td></tr>})}</tbody></table></div></section>}
 const done=chairs.filter(c=>complete(c.id)).length;return <section className="chair-workspace"><div className="chair-tracker-head"><div><p className="eyebrow">CHAIR PARTS TRACKER</p><h2>Built chairs</h2><p>Installed parts are kept separate from loose inventory.</p></div><button className="primary" onClick={add}>+ Add chair folder</button></div><div className="chair-metrics"><article><span>Total chairs</span><strong>{chairs.length}</strong></article><article><span>Fully built</span><strong>{done}</strong></article><article><span>In progress</span><strong>{chairs.length-done}</strong></article></div><div className="chair-grid">{chairs.map(c=>{const a=look(c);return <button className="chair-folder" key={c.id} onClick={()=>setActive(c.id)}><span className="wheel-letter">{a.wheelPosition}</span><div className="swatch-pair"><span><i style={{background:a.chairColor}}/>Chair</span><span><i style={{background:a.remoteColor}}/>Remote</span></div><strong>{c.name}</strong><small>{assets.filter(x=>x.chairId===c.id).length||parts.filter(p=>p.chairId===c.id&&p.quantity>0).length} tracked records</small><span className={`chair-state ${complete(c.id)?"complete":"progress"}`}>{complete(c.id)?"Fully built":"In progress"}</span></button>})}{!chairs.length&&<div className="empty">No tracked chairs yet. Add a folder, or use New Chair to record a complete build.</div>}</div></section>
}
