"use client";
import {useEffect,useMemo,useState} from "react";

type Chair={id:number;name:string};
type Asset={id:number;assetTag:string;kind:"Jetson"|"PCB";model:string;serialNumber:string;chairId:number|null;chairName:string|null;notes:string;updatedAt:string;updatedBy:string;lastFlashedAt:string|null;lastImageName:string|null;lastVersion:string|null;lastFlashedBy:string|null};
type Flash={id:number;assetId:number;flashedAt:string;imageName:string;version:string;notes:string;flashedBy:string;createdAt:string};
const blank={id:0,assetTag:"",kind:"Jetson" as const,model:"",serialNumber:"",chairId:null as number|null,notes:""};

export default function HardwareTracker(){
 const[assets,setAssets]=useState<Asset[]>([]),[chairs,setChairs]=useState<Chair[]>([]),[flashes,setFlashes]=useState<Flash[]>([]),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
 const[query,setQuery]=useState(""),[kind,setKind]=useState("all"),[editor,setEditor]=useState<typeof blank|null>(null),[flashAsset,setFlashAsset]=useState<Asset|null>(null),[historyAsset,setHistoryAsset]=useState<Asset|null>(null);
 const[flashForm,setFlashForm]=useState({flashedAt:new Date().toISOString().slice(0,16),imageName:"",version:"",notes:""});
 async function load(){setBusy(true);const r=await fetch("/api/hardware-assets"),d=await r.json();setAssets(d.assets||[]);setChairs(d.chairs||[]);setFlashes(d.flashes||[]);setBusy(false)}
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>assets.filter(a=>(kind==="all"||a.kind===kind)&&(!query||[a.assetTag,a.model,a.serialNumber,a.chairName].some(v=>(v||"").toLowerCase().includes(query.toLowerCase())))),[assets,kind,query]);
 const stats={total:assets.length,assigned:assets.filter(a=>a.chairId).length,never:assets.filter(a=>!a.lastFlashedAt).length};
 async function saveAsset(e:React.FormEvent){e.preventDefault();if(!editor)return;const r=await fetch(editor.id?`/api/hardware-assets/${editor.id}`:"/api/hardware-assets",{method:editor.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editor)}),d=await r.json();if(!r.ok)return setMessage(d.error||"The board could not be saved.");setEditor(null);setMessage(editor.id?"Board updated.":"Board added.");await load()}
 async function remove(){if(!editor?.id||!confirm(`Delete ${editor.assetTag} and its flash history?`))return;const r=await fetch(`/api/hardware-assets/${editor.id}`,{method:"DELETE"}),d=await r.json();if(!r.ok)return setMessage(d.error||"The board could not be deleted.");setEditor(null);setMessage("Board deleted.");await load()}
 function startFlash(a:Asset){setFlashAsset(a);setFlashForm({flashedAt:new Date().toISOString().slice(0,16),imageName:"",version:"",notes:""})}
 async function saveFlash(e:React.FormEvent){e.preventDefault();if(!flashAsset)return;const r=await fetch(`/api/hardware-assets/${flashAsset.id}/flashes`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(flashForm)}),d=await r.json();if(!r.ok)return setMessage(d.error||"The flash record could not be saved.");setFlashAsset(null);setMessage(`Flash recorded for ${flashAsset.assetTag}.`);await load()}
 return <section className="hardware-workspace">
  <div className="hardware-head"><div><p className="eyebrow">PCB / JETSON TRACKER</p><h2>Boards, software, and chair assignments</h2><p>Track every physical board, what was flashed to it, when it was flashed, and where it is installed.</p></div><button className="primary" onClick={()=>setEditor({...blank})}>+ Add Jetson or PCB</button></div>
  {message&&<p className="tracker-message">{message}</p>}
  <div className="hardware-metrics"><article><span>Total boards</span><strong>{stats.total}</strong></article><article><span>Assigned to chairs</span><strong>{stats.assigned}</strong></article><article className={stats.never?"warn":""}><span>Never flashed / unknown</span><strong>{stats.never}</strong></article></div>
  <div className="hardware-toolbar"><input placeholder="Search asset tag, model, serial, or chair…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All board types</option><option>Jetson</option><option>PCB</option></select><button className="ghost" onClick={load}>Refresh</button></div>
  <div className="table-wrap"><table><thead><tr><th>Board</th><th>Serial number</th><th>Installed on</th><th>Last flashed</th><th>Software / image</th><th></th></tr></thead><tbody>{shown.map(a=><tr key={a.id}><td><strong>{a.assetTag}</strong><small>{a.kind} · {a.model||"Model not set"}</small></td><td>{a.serialNumber||"—"}</td><td><span className={`assignment ${a.chairId?"installed":"unassigned"}`}>{a.chairName||"Unassigned"}</span></td><td>{a.lastFlashedAt?new Date(a.lastFlashedAt).toLocaleString():"Not recorded"}<small>{a.lastFlashedBy?`by ${a.lastFlashedBy}`:""}</small></td><td>{a.lastImageName||"—"}<small>{a.lastVersion||""}</small></td><td><div className="row-actions"><button onClick={()=>startFlash(a)}>Record flash</button><button onClick={()=>setHistoryAsset(a)}>History</button><button onClick={()=>setEditor({id:a.id,assetTag:a.assetTag,kind:a.kind,model:a.model,serialNumber:a.serialNumber,chairId:a.chairId,notes:a.notes})}>Edit</button></div></td></tr>)}</tbody></table>{!busy&&!shown.length&&<div className="empty">No boards match this view.</div>}</div>
  {editor&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setEditor(null)}><form className="modal item-modal" onSubmit={saveAsset}><button type="button" className="close" onClick={()=>setEditor(null)}>×</button><p className="eyebrow">{editor.id?"EDIT BOARD":"ADD BOARD"}</p><h2>{editor.id?editor.assetTag:"New Jetson or PCB"}</h2><div className="form-grid"><label>Asset tag<input required placeholder="JET-001-003" value={editor.assetTag} onChange={e=>setEditor({...editor,assetTag:e.target.value})}/></label><label>Type<select value={editor.kind} onChange={e=>setEditor({...editor,kind:e.target.value as "Jetson"|"PCB"})}><option>Jetson</option><option>PCB</option></select></label><label>Model<input placeholder="Jetson AGX Orin 64GB" value={editor.model} onChange={e=>setEditor({...editor,model:e.target.value})}/></label><label>Serial number<input value={editor.serialNumber} onChange={e=>setEditor({...editor,serialNumber:e.target.value})}/></label><label className="wide">Installed on chair<select value={editor.chairId??""} onChange={e=>setEditor({...editor,chairId:e.target.value?Number(e.target.value):null})}><option value="">Unassigned / spare</option>{chairs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="wide">Notes<textarea value={editor.notes} onChange={e=>setEditor({...editor,notes:e.target.value})}/></label></div><div className="modal-actions">{editor.id>0&&<button type="button" className="delete-item" onClick={remove}>Delete board</button>}<button type="button" className="ghost" onClick={()=>setEditor(null)}>Cancel</button><button className="primary">Save board</button></div></form></div>}
  {flashAsset&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setFlashAsset(null)}><form className="modal" onSubmit={saveFlash}><button type="button" className="close" onClick={()=>setFlashAsset(null)}>×</button><p className="eyebrow">RECORD FLASH</p><h2>{flashAsset.assetTag}</h2><label>Date and time<input required type="datetime-local" value={flashForm.flashedAt} onChange={e=>setFlashForm({...flashForm,flashedAt:e.target.value})}/></label><label>Software / image name<input required placeholder="MagicMode Chair Image" value={flashForm.imageName} onChange={e=>setFlashForm({...flashForm,imageName:e.target.value})}/></label><label>Version / build<input placeholder="v2.4.1 or commit ID" value={flashForm.version} onChange={e=>setFlashForm({...flashForm,version:e.target.value})}/></label><label>Notes<textarea placeholder="Changes, configuration, or reason for flash" value={flashForm.notes} onChange={e=>setFlashForm({...flashForm,notes:e.target.value})}/></label><div className="modal-actions"><button type="button" className="ghost" onClick={()=>setFlashAsset(null)}>Cancel</button><button className="primary">Save flash record</button></div></form></div>}
  {historyAsset&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setHistoryAsset(null)}><section className="modal history-panel"><button type="button" className="close" onClick={()=>setHistoryAsset(null)}>×</button><p className="eyebrow">FLASH HISTORY</p><h2>{historyAsset.assetTag}</h2><div className="flash-history">{flashes.filter(f=>f.assetId===historyAsset.id).map(f=><article key={f.id}><div><strong>{f.imageName}</strong><span>{f.version||"No version entered"}</span></div><div><time>{new Date(f.flashedAt).toLocaleString()}</time><small>Flashed by {f.flashedBy}</small></div>{f.notes&&<p>{f.notes}</p>}</article>)}{!flashes.some(f=>f.assetId===historyAsset.id)&&<div className="empty">No flash history has been recorded yet.</div>}</div></section></div>}
 </section>
}
