"use client";

import { useEffect, useMemo, useState } from "react";

type Item = { id:number; partNumber:string; name:string; description:string; qtyNeeded:number; qtyOnHand:number; unitCost:number|null; unit:string; supplier:string; leadTime:string; bomLevel:number|null; notes:string; purchaseUrl:string };
type Tx = { id:number; itemId:number; itemName:string; kind:"receive"|"use"|"adjust"; quantity:number; reference:string; note:string; createdAt:string };

const money = new Intl.NumberFormat("en-US", { style:"currency", currency:"USD" });
const buildCoverage=(item:Item)=>item.qtyNeeded>0?Math.floor(item.qtyOnHand/item.qtyNeeded):0;
const stockStatus=(item:Item)=>item.qtyOnHand<=0?"out":buildCoverage(item)<5?"low":"ready";
const blankItem:Item={id:0,partNumber:"",name:"",description:"",qtyNeeded:1,qtyOnHand:0,unitCost:null,unit:"pcs",supplier:"",leadTime:"",bomLevel:1,notes:"",purchaseUrl:""};

export default function Home() {
  const [items,setItems]=useState<Item[]>([]); const [transactions,setTransactions]=useState<Tx[]>([]);
  const [search,setSearch]=useState(""); const [filter,setFilter]=useState("all"); const [tab,setTab]=useState<"inventory"|"activity">("inventory");
  const [busy,setBusy]=useState(true); const [dialog,setDialog]=useState<{kind:"receive"|"use"|"adjust";item:Item}|null>(null);
  const [qty,setQty]=useState("1"); const [reference,setReference]=useState(""); const [note,setNote]=useState("");
  const [message,setMessage]=useState("");
  const [linkItem,setLinkItem]=useState<Item|null>(null); const [purchaseUrl,setPurchaseUrl]=useState("");
  const [itemEditor,setItemEditor]=useState<Item|null>(null); const [isNewItem,setIsNewItem]=useState(false);

  async function refresh(){ setBusy(true); const [a,b]=await Promise.all([fetch("/api/items"),fetch("/api/transactions")]); setItems(await a.json()); setTransactions(await b.json()); setBusy(false); }
  useEffect(()=>{refresh().catch(()=>setBusy(false));},[]);
  const stats=useMemo(()=>({total:items.length, low:items.filter(i=>buildCoverage(i)<5).length, builds:items.length?Math.min(...items.filter(i=>i.qtyNeeded>0).map(buildCoverage)):0, value:items.reduce((s,i)=>s+i.qtyOnHand*(i.unitCost||0),0)}),[items]);
  const shown=items.filter(i=>{const q=search.toLowerCase(); const matches=!q||[i.partNumber,i.name,i.description,i.supplier].some(v=>(v||"").toLowerCase().includes(q)); return matches&&(filter==="all"||filter===stockStatus(i));});
  async function submit(e:React.FormEvent){e.preventDefault(); if(!dialog)return; await fetch("/api/transactions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({itemId:dialog.item.id,kind:dialog.kind,quantity:Number(qty),reference,note})}); setDialog(null);setQty("1");setReference("");setNote("");await refresh();}
  function open(kind:"receive"|"use"|"adjust",item:Item){setDialog({kind,item});setQty("1");setReference("");setNote("");}
  async function newChair(){if(!confirm("Use one complete build's worth of every BOM item for a new chair?"))return;setBusy(true);const r=await fetch("/api/new-chair",{method:"POST"});const data=await r.json();setMessage(r.ok?"New chair recorded — one complete BOM build was consumed.":data.error||"The chair could not be recorded.");await refresh();}
  async function undo(){if(!confirm("Undo the latest inventory action?"))return;setBusy(true);const r=await fetch("/api/undo",{method:"POST"});const data=await r.json();setMessage(r.ok?data.message:data.error||"Nothing could be undone.");await refresh();}
  function editLink(item:Item){setLinkItem(item);setPurchaseUrl(item.purchaseUrl||"");}
  async function saveLink(e:React.FormEvent){e.preventDefault();if(!linkItem)return;const r=await fetch(`/api/items/${linkItem.id}/purchase-link`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({url:purchaseUrl.trim()})});const data=await r.json();if(!r.ok){setMessage(data.error||"The purchase link could not be saved.");return;}setLinkItem(null);setMessage(purchaseUrl.trim()?"Purchase link saved.":"Purchase link removed.");await refresh();}
  function newItem(){setIsNewItem(true);setItemEditor({...blankItem});}
  function editItem(item:Item){setIsNewItem(false);setItemEditor({...item});}
  function field<K extends keyof Item>(key:K,value:Item[K]){setItemEditor(current=>current?{...current,[key]:value}:current);}
  async function saveItem(e:React.FormEvent){e.preventDefault();if(!itemEditor)return;const path=isNewItem?"/api/items":`/api/items/${itemEditor.id}`;const r=await fetch(path,{method:isNewItem?"POST":"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(itemEditor)});const data=await r.json();if(!r.ok){setMessage(data.error||"The item could not be saved.");return;}setItemEditor(null);setMessage(isNewItem?"New inventory item added.":"Inventory item updated.");await refresh();}
  async function deleteItem(){if(!itemEditor||isNewItem)return;if(!confirm(`Delete ${itemEditor.name}? This also removes its activity history and purchase link.`))return;const r=await fetch(`/api/items/${itemEditor.id}`,{method:"DELETE"});const data=await r.json();if(!r.ok){setMessage(data.error||"The item could not be deleted.");return;}setItemEditor(null);setMessage("Inventory item deleted.");await refresh();}

  return <main>
    <header className="topbar"><div className="brand"><span className="mark">V</span><div><strong>Vishnu Inventory</strong><small>Production materials control</small></div></div><div className="header-actions"><button className="ghost undo" disabled={!transactions.length||busy} onClick={undo}>↶ Undo</button><button className="chair" disabled={busy} onClick={newChair}>+ New Chair</button><button className="primary receive-top" onClick={()=>items[0]&&open("receive",items[0])}>+ Receive stock</button></div></header>
    {message&&<div className="notice"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}
    <section className="hero"><div><p className="eyebrow">INVENTORY OVERVIEW</p><h1>Know what you have.<br/><span>Build with confidence.</span></h1><p className="lede">Live stock levels from your BOM, with every package received and every item used recorded in one place.</p></div><div className="build-card"><span>BUILD READINESS</span><strong>{stats.builds}</strong><p>complete unit{stats.builds===1?"":"s"} ready</p><div className="meter"><i style={{width:`${Math.min(100,stats.builds*20)}%`}}/></div><small>Based on the tightest BOM component</small></div></section>
    <section className="stats"><article><span>Total parts</span><strong>{stats.total}</strong><small>Active BOM lines</small></article><article className={stats.low?"warn":""}><span>Needs attention</span><strong>{stats.low}</strong><small>Below 5 builds</small></article><article><span>Inventory value</span><strong>{money.format(stats.value)}</strong><small>Known unit costs</small></article><article><span>Recent movement</span><strong>{transactions.length}</strong><small>Logged transactions</small></article></section>
    <nav className="tabs"><button className={tab==="inventory"?"active":""} onClick={()=>setTab("inventory")}>Inventory</button><button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}>Activity log</button></nav>
    {tab==="inventory"?<section className="panel"><div className="toolbar"><div className="search"><span>⌕</span><input aria-label="Search inventory" placeholder="Search part, description, or supplier…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filters">{[["all","All"],["ready","Ready"],["low","Low"],["out","Out"]].map(([v,l])=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{l}</button>)}</div><button className="primary new-item" onClick={newItem}>+ New Item</button></div>
      <div className="table-wrap"><table><thead><tr><th>Part / material</th><th>Supplier</th><th>On hand</th><th>Per build</th><th>Coverage</th><th>Status</th><th></th></tr></thead><tbody>{shown.map(i=>{const coverage=buildCoverage(i); const status=stockStatus(i); const label=status==="out"?"Out":status==="low"?"Low":"Ready";return <tr key={i.id}><td><strong>{i.name}</strong><small>{i.partNumber||"No part number"} · {i.description||"No description"}</small></td><td>{i.supplier||"—"}<small>{i.leadTime||"Lead time not set"}</small></td><td><b>{i.qtyOnHand}</b> {i.unit}</td><td>{i.qtyNeeded} {i.unit}</td><td><strong>{coverage}</strong> build{coverage===1?"":"s"}</td><td><span className={`badge ${status}`}>{label}</span></td><td><div className="row-actions"><button className="edit-item" onClick={()=>editItem(i)}>Edit</button>{i.purchaseUrl?<><a className="buy" href={i.purchaseUrl} target="_blank" rel="noreferrer">Buy ↗</a><button onClick={()=>editLink(i)}>Edit link</button></>:<button className="add-link" onClick={()=>editLink(i)}>+ Link</button>}<button onClick={()=>open("receive",i)}>Receive</button><button onClick={()=>open("use",i)}>Use</button><button aria-label="Adjust stock" onClick={()=>open("adjust",i)}>•••</button></div></td></tr>})}</tbody></table>{!busy&&!shown.length&&<div className="empty">No inventory items match that view.</div>}</div>
    </section>:<section className="panel activity"><div className="activity-head"><div><h2>Stock movement</h2><p>A permanent audit trail of receipts, usage, and corrections.</p></div><button className="ghost" onClick={()=>refresh()}>Refresh</button></div>{transactions.map(t=><article key={t.id}><span className={`tx-icon ${t.kind}`}>{t.kind==="receive"?"↓":t.kind==="use"?"↑":"↔"}</span><div><strong>{t.itemName}</strong><p>{t.kind==="receive"?"Received":t.kind==="use"?"Used":"Adjusted"} {t.quantity} {t.reference&&`· ${t.reference}`}</p>{t.note&&<small>{t.note}</small>}</div><time>{new Date(t.createdAt).toLocaleString()}</time></article>)}{!transactions.length&&<div className="empty">Your first stock movement will appear here.</div>}</section>}
    {dialog&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setDialog(null)}><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={()=>setDialog(null)}>×</button><span className={`modal-icon ${dialog.kind}`}>{dialog.kind==="receive"?"↓":dialog.kind==="use"?"↑":"↔"}</span><p className="eyebrow">{dialog.kind.toUpperCase()} STOCK</p><h2>{dialog.item.name}</h2><p className="muted">Current balance: <b>{dialog.item.qtyOnHand} {dialog.item.unit}</b></p><label>{dialog.kind==="adjust"?"Set quantity on hand":"Quantity"}<input autoFocus min="0" step="any" type="number" required value={qty} onChange={e=>setQty(e.target.value)}/></label><label>{dialog.kind==="receive"?"Package / PO reference":"Job / build reference"}<input placeholder={dialog.kind==="receive"?"e.g. PO-1042 or tracking number":"e.g. Build 027"} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Note <span>optional</span><textarea placeholder="Lot number, reason, or other detail" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="modal-actions"><button type="button" className="ghost" onClick={()=>setDialog(null)}>Cancel</button><button className="primary" type="submit">Save {dialog.kind}</button></div></form></div>}
    {linkItem&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setLinkItem(null)}><form className="modal" onSubmit={saveLink}><button type="button" className="close" onClick={()=>setLinkItem(null)}>×</button><span className="modal-icon">↗</span><p className="eyebrow">PURCHASE LINK</p><h2>{linkItem.name}</h2><p className="muted">Paste the supplier or product page used to reorder this item.</p><label>Purchase URL<input autoFocus type="url" placeholder="https://supplier.com/product" value={purchaseUrl} onChange={e=>setPurchaseUrl(e.target.value)}/></label><div className="modal-actions">{linkItem.purchaseUrl&&<button type="button" className="remove-link" onClick={()=>setPurchaseUrl("")}>Remove link</button>}<button type="button" className="ghost" onClick={()=>setLinkItem(null)}>Cancel</button><button className="primary" type="submit">Save link</button></div></form></div>}
    {itemEditor&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setItemEditor(null)}><form className="modal item-modal" onSubmit={saveItem}><button type="button" className="close" onClick={()=>setItemEditor(null)}>×</button><p className="eyebrow">{isNewItem?"NEW INVENTORY ITEM":"EDIT INVENTORY ITEM"}</p><h2>{isNewItem?"Add a material":itemEditor.name}</h2><div className="form-grid"><label>Part number<input value={itemEditor.partNumber} onChange={e=>field("partNumber",e.target.value)}/></label><label>Part name<input required value={itemEditor.name} onChange={e=>field("name",e.target.value)}/></label><label className="wide">Description<input value={itemEditor.description} onChange={e=>field("description",e.target.value)}/></label><label>Quantity per chair<input required min="0.0001" step="any" type="number" value={itemEditor.qtyNeeded} onChange={e=>field("qtyNeeded",Number(e.target.value))}/></label><label>Quantity on hand<input required min="0" step="any" type="number" value={itemEditor.qtyOnHand} onChange={e=>field("qtyOnHand",Number(e.target.value))}/></label><label>Unit<input required value={itemEditor.unit} onChange={e=>field("unit",e.target.value)}/></label><label>Unit cost<input min="0" step="0.01" type="number" value={itemEditor.unitCost??""} onChange={e=>field("unitCost",e.target.value===""?null:Number(e.target.value))}/></label><label>Supplier<input value={itemEditor.supplier} onChange={e=>field("supplier",e.target.value)}/></label><label>Lead time<input value={itemEditor.leadTime} onChange={e=>field("leadTime",e.target.value)}/></label><label>BOM level<input min="0" step="1" type="number" value={itemEditor.bomLevel??""} onChange={e=>field("bomLevel",e.target.value===""?null:Number(e.target.value))}/></label><label className="wide">Purchase URL<input type="url" value={itemEditor.purchaseUrl} onChange={e=>field("purchaseUrl",e.target.value)}/></label><label className="wide">Notes<textarea value={itemEditor.notes} onChange={e=>field("notes",e.target.value)}/></label></div><div className="modal-actions">{!isNewItem&&<button type="button" className="delete-item" onClick={deleteItem}>Delete item</button>}<button type="button" className="ghost" onClick={()=>setItemEditor(null)}>Cancel</button><button className="primary" type="submit">{isNewItem?"Add item":"Save changes"}</button></div></form></div>}
  </main>
}
