"use client";

import { useEffect, useMemo, useState } from "react";

type Item = { id:number; partNumber:string; name:string; description:string; qtyNeeded:number; qtyOnHand:number; unitCost:number|null; unit:string; supplier:string; leadTime:string; bomLevel:number|null; notes:string };
type Tx = { id:number; itemId:number; itemName:string; kind:"receive"|"use"|"adjust"; quantity:number; reference:string; note:string; createdAt:string };

const money = new Intl.NumberFormat("en-US", { style:"currency", currency:"USD" });
const buildCoverage=(item:Item)=>item.qtyNeeded>0?Math.floor(item.qtyOnHand/item.qtyNeeded):0;
const stockStatus=(item:Item)=>item.qtyOnHand<=0?"out":buildCoverage(item)<5?"low":"ready";

export default function Home() {
  const [items,setItems]=useState<Item[]>([]); const [transactions,setTransactions]=useState<Tx[]>([]);
  const [search,setSearch]=useState(""); const [filter,setFilter]=useState("all"); const [tab,setTab]=useState<"inventory"|"activity">("inventory");
  const [busy,setBusy]=useState(true); const [dialog,setDialog]=useState<{kind:"receive"|"use"|"adjust";item:Item}|null>(null);
  const [qty,setQty]=useState("1"); const [reference,setReference]=useState(""); const [note,setNote]=useState("");
  const [message,setMessage]=useState("");

  async function refresh(){ setBusy(true); const [a,b]=await Promise.all([fetch("/api/items"),fetch("/api/transactions")]); setItems(await a.json()); setTransactions(await b.json()); setBusy(false); }
  useEffect(()=>{refresh().catch(()=>setBusy(false));},[]);
  const stats=useMemo(()=>({total:items.length, low:items.filter(i=>buildCoverage(i)<5).length, builds:items.length?Math.min(...items.filter(i=>i.qtyNeeded>0).map(buildCoverage)):0, value:items.reduce((s,i)=>s+i.qtyOnHand*(i.unitCost||0),0)}),[items]);
  const shown=items.filter(i=>{const q=search.toLowerCase(); const matches=!q||[i.partNumber,i.name,i.description,i.supplier].some(v=>(v||"").toLowerCase().includes(q)); return matches&&(filter==="all"||filter===stockStatus(i));});
  async function submit(e:React.FormEvent){e.preventDefault(); if(!dialog)return; await fetch("/api/transactions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({itemId:dialog.item.id,kind:dialog.kind,quantity:Number(qty),reference,note})}); setDialog(null);setQty("1");setReference("");setNote("");await refresh();}
  function open(kind:"receive"|"use"|"adjust",item:Item){setDialog({kind,item});setQty("1");setReference("");setNote("");}
  async function newChair(){if(!confirm("Use one complete build's worth of every BOM item for a new chair?"))return;setBusy(true);const r=await fetch("/api/new-chair",{method:"POST"});const data=await r.json();setMessage(r.ok?"New chair recorded — one complete BOM build was consumed.":data.error||"The chair could not be recorded.");await refresh();}
  async function undo(){if(!confirm("Undo the latest inventory action?"))return;setBusy(true);const r=await fetch("/api/undo",{method:"POST"});const data=await r.json();setMessage(r.ok?data.message:data.error||"Nothing could be undone.");await refresh();}

  return <main>
    <header className="topbar"><div className="brand"><span className="mark">V</span><div><strong>Vishnu Inventory</strong><small>Production materials control</small></div></div><div className="header-actions"><button className="ghost undo" disabled={!transactions.length||busy} onClick={undo}>↶ Undo</button><button className="chair" disabled={busy} onClick={newChair}>+ New Chair</button><button className="primary receive-top" onClick={()=>items[0]&&open("receive",items[0])}>+ Receive stock</button></div></header>
    {message&&<div className="notice"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}
    <section className="hero"><div><p className="eyebrow">INVENTORY OVERVIEW</p><h1>Know what you have.<br/><span>Build with confidence.</span></h1><p className="lede">Live stock levels from your BOM, with every package received and every item used recorded in one place.</p></div><div className="build-card"><span>BUILD READINESS</span><strong>{stats.builds}</strong><p>complete unit{stats.builds===1?"":"s"} ready</p><div className="meter"><i style={{width:`${Math.min(100,stats.builds*20)}%`}}/></div><small>Based on the tightest BOM component</small></div></section>
    <section className="stats"><article><span>Total parts</span><strong>{stats.total}</strong><small>Active BOM lines</small></article><article className={stats.low?"warn":""}><span>Needs attention</span><strong>{stats.low}</strong><small>Below 5 builds</small></article><article><span>Inventory value</span><strong>{money.format(stats.value)}</strong><small>Known unit costs</small></article><article><span>Recent movement</span><strong>{transactions.length}</strong><small>Logged transactions</small></article></section>
    <nav className="tabs"><button className={tab==="inventory"?"active":""} onClick={()=>setTab("inventory")}>Inventory</button><button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}>Activity log</button></nav>
    {tab==="inventory"?<section className="panel"><div className="toolbar"><div className="search"><span>⌕</span><input aria-label="Search inventory" placeholder="Search part, description, or supplier…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filters">{[["all","All"],["ready","Ready"],["low","Low"],["out","Out"]].map(([v,l])=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{l}</button>)}</div></div>
      <div className="table-wrap"><table><thead><tr><th>Part / material</th><th>Supplier</th><th>On hand</th><th>Per build</th><th>Coverage</th><th>Status</th><th></th></tr></thead><tbody>{shown.map(i=>{const coverage=buildCoverage(i); const status=stockStatus(i); const label=status==="out"?"Out":status==="low"?"Low":"Ready";return <tr key={i.id}><td><strong>{i.name}</strong><small>{i.partNumber||"No part number"} · {i.description||"No description"}</small></td><td>{i.supplier||"—"}<small>{i.leadTime||"Lead time not set"}</small></td><td><b>{i.qtyOnHand}</b> {i.unit}</td><td>{i.qtyNeeded} {i.unit}</td><td><strong>{coverage}</strong> build{coverage===1?"":"s"}</td><td><span className={`badge ${status}`}>{label}</span></td><td><div className="row-actions"><button onClick={()=>open("receive",i)}>Receive</button><button onClick={()=>open("use",i)}>Use</button><button aria-label="Adjust stock" onClick={()=>open("adjust",i)}>•••</button></div></td></tr>})}</tbody></table>{!busy&&!shown.length&&<div className="empty">No inventory items match that view.</div>}</div>
    </section>:<section className="panel activity"><div className="activity-head"><div><h2>Stock movement</h2><p>A permanent audit trail of receipts, usage, and corrections.</p></div><button className="ghost" onClick={()=>refresh()}>Refresh</button></div>{transactions.map(t=><article key={t.id}><span className={`tx-icon ${t.kind}`}>{t.kind==="receive"?"↓":t.kind==="use"?"↑":"↔"}</span><div><strong>{t.itemName}</strong><p>{t.kind==="receive"?"Received":t.kind==="use"?"Used":"Adjusted"} {t.quantity} {t.reference&&`· ${t.reference}`}</p>{t.note&&<small>{t.note}</small>}</div><time>{new Date(t.createdAt).toLocaleString()}</time></article>)}{!transactions.length&&<div className="empty">Your first stock movement will appear here.</div>}</section>}
    {dialog&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setDialog(null)}><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={()=>setDialog(null)}>×</button><span className={`modal-icon ${dialog.kind}`}>{dialog.kind==="receive"?"↓":dialog.kind==="use"?"↑":"↔"}</span><p className="eyebrow">{dialog.kind.toUpperCase()} STOCK</p><h2>{dialog.item.name}</h2><p className="muted">Current balance: <b>{dialog.item.qtyOnHand} {dialog.item.unit}</b></p><label>{dialog.kind==="adjust"?"Set quantity on hand":"Quantity"}<input autoFocus min="0" step="any" type="number" required value={qty} onChange={e=>setQty(e.target.value)}/></label><label>{dialog.kind==="receive"?"Package / PO reference":"Job / build reference"}<input placeholder={dialog.kind==="receive"?"e.g. PO-1042 or tracking number":"e.g. Build 027"} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Note <span>optional</span><textarea placeholder="Lot number, reason, or other detail" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="modal-actions"><button type="button" className="ghost" onClick={()=>setDialog(null)}>Cancel</button><button className="primary" type="submit">Save {dialog.kind}</button></div></form></div>}
  </main>
}
