/** Cloudflare Worker entry point for the vinext-starter template. */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

interface Env {
  ASSETS: Fetcher;
  DB: D1Database;
  FILES: R2Bucket;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

const worker = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname.startsWith("/api/")) return handleApi(request, env, url);

    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    return handler.fetch(request, env, ctx);
  },
};

const seed=[
 ["","Jetson Orin AGX","Compute",1,2,1999.99,"pcs","Amazon/Nvidia","",1,"Edge Compute"],["CU31 CXLCC BX H03R1","See3 Cam without enclosure","Top Camera",1,3,249,"cameras","e-con Systems","2 months",1,""],["CU31 CHLCC H03R1","See3 Cam with enclosure","Side Cameras and rear",3,4,289,"cameras","e-con Systems","2 months",1,""],["DSL392B-NIR-F 2.0 / DSL392B-650-F 2.0","Camera Top Lens","Camera Lens",1,15,99,"lenses","Sunex","2 days",2,""],["","Camera Rear Housing","3d print",1,0,null,"pcs","SunPe","",1,""],["CLA020-PC","Camera Lens Mount","M12 Lens Mount, 20mm Spacing, 10mm Height",1,29,4.5,"pcs","CommonLands","2 days",2,""],["","Camera Side Housing","3d print",2,0,null,"pcs","SunPe","",1,""],["D51601","R-NET Development Kit","3pc component set",1,40,133.9,"pcs","Curtiss-Wright","2 months",2,""],["P77978","R-NET JSM Bulkhead Retaining Clip","u-clip",1,95,1.61,"pcs","Curtiss-Wright","1 month",3,""],["P78039","R-Net Rebus Panel Mount Connector","surface plug",1,0,5.15,"pcs","Curtiss-Wright","",3,""],["","PCB Fab board","Software Board",1,3,40,"boards","PCB Unlimited","2 weeks",1,""],["","Display screen","Touch Screen Display",1,16,54.68,"screens","Crystal Displays","4 weeks",1,""],["","Display Connector","HDMI to Displayport",1,0,7.99,"pcs","Benfei","",2,""],["","Display Power Cable","USB-A to micro-usb",1,10,null,"pcs","","",2,""],["","USB C to USB C Cable","1.6 FT, Right Angle 20Gbps Data Transfer",2,23,null,"pcs","Amazon","",3,""],["","Power cable (RNET-Jetson)","",1,0,null,"pcs","","",3,""],["","USB C to USB A 20Gbps Data Cable","4FT, For Boom Camera",1,5,null,"pcs","","",3,""],["","USB-C to 4-Port USB-C","3.2 Gen2 Ports Hub",1,2,null,"pcs","Amazon","",3,""],["","Jetson Housing (2 pc.)","3d print",1,0,1512,"pcs","SunPe","",1,""],["","Camera Boom","3d print",1,1,null,"pcs","SunPe","",1,""],["","Speaker","",1,25,null,"speakers","Amazon/Honkyob","",1,""],["91290A012","Side Camera Screws","M2 x 0.4mm, 5mm Socket Head",8,181,null,"screws","McMaster-Carr","2 days",3,""],["91290A320","Mounting Screws","M6 x 1mm, 15mm Socket Head",8,170,null,"screws","McMaster-Carr","2 days",3,""],["96887A121","Low-Strength Steel Square Nut","M6 x 1mm Thread",8,216,null,"nuts","McMaster-Carr","2 days",3,""],["9031A112","Nylon-Insert Locknut","M4 x 0.7mm Thread",4,0,null,"nuts","McMaster-Carr","2 days",3,""],["95893A179","Thread-Forming Screws For Plastic","M2.5 x 8mm",4,91,null,"screws","McMaster-Carr","2 days",3,""],["99461A941","Phillips Thread-Forming Screws","M3, 8mm Long",4,0,null,"screws","McMaster-Carr","2 days",3,""],["","Battery","Batteries for Chair",2,2,299.99,"batteries","","",null,""]
];
async function initialize(db:D1Database){await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, part_number TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, qty_needed REAL NOT NULL, qty_on_hand REAL NOT NULL, unit_cost REAL, unit TEXT NOT NULL, supplier TEXT NOT NULL, lead_time TEXT NOT NULL, bom_level INTEGER, notes TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'Other')"),db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS items_identity_idx ON items(LOWER(TRIM(part_number)),LOWER(TRIM(name)))"),db.prepare("CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY AUTOINCREMENT, item_id INTEGER NOT NULL, kind TEXT NOT NULL, quantity REAL NOT NULL, reference TEXT NOT NULL, note TEXT NOT NULL, created_at TEXT NOT NULL)"),db.prepare("CREATE INDEX IF NOT EXISTS transactions_item_idx ON transactions(item_id)"),db.prepare("CREATE TABLE IF NOT EXISTS purchase_links (item_id INTEGER PRIMARY KEY NOT NULL, url TEXT NOT NULL, updated_at TEXT NOT NULL)"),db.prepare("CREATE TABLE IF NOT EXISTS chairs (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, chair_color TEXT NOT NULL DEFAULT '#3274bb', remote_color TEXT NOT NULL DEFAULT '#14161e', notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL)"),db.prepare("CREATE TABLE IF NOT EXISTS chair_parts (chair_id INTEGER NOT NULL, item_id INTEGER NOT NULL, quantity REAL NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'Installed', notes TEXT NOT NULL DEFAULT '', updated_by TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL, PRIMARY KEY(chair_id,item_id))"),db.prepare("CREATE INDEX IF NOT EXISTS chair_parts_chair_idx ON chair_parts(chair_id)")]);const count=await db.prepare("SELECT COUNT(*) count FROM items").first<{count:number}>();if(!count?.count)await db.batch(seed.map(x=>db.prepare("INSERT OR IGNORE INTO items(part_number,name,description,qty_needed,qty_on_hand,unit_cost,unit,supplier,lead_time,bom_level,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(...x)));}
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json"}});
const bytesToBase64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes));
const sha256Hex=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,"0")).join("");
async function passwordHash(password:string,saltBase64:string){const salt=Uint8Array.from(atob(saltBase64),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);return bytesToBase64(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:100000,hash:"SHA-256"},key,256)));}
function cookieValue(request:Request,name:string){const cookie=request.headers.get("cookie")||"";for(const part of cookie.split(";")){const [key,...rest]=part.trim().split("=");if(key===name)return rest.join("=");}return "";}
async function currentUser(request:Request,db:D1Database){const token=cookieValue(request,"mm_session");if(!token)return null;const hash=await sha256Hex(token);return db.prepare("SELECT u.id,u.name FROM app_sessions s JOIN app_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1").bind(hash,new Date().toISOString()).first<{id:number;name:string}>();}
async function handleApi(request:Request,env:Env,url:URL){await initialize(env.DB);
 if(url.pathname==="/api/auth/users"&&request.method==="GET"){const r=await env.DB.prepare("SELECT id,name FROM app_users WHERE active=1 ORDER BY name").all();return json(r.results);}
 if(url.pathname==="/api/auth/login"&&request.method==="POST"){const b=await request.json() as {userId?:number;password?:string};const user=await env.DB.prepare("SELECT id,name FROM app_users WHERE id=? AND active=1").bind(Number(b.userId)).first<{id:number;name:string}>();const settings=(await env.DB.prepare("SELECT key,value FROM app_settings WHERE key IN ('password_salt','password_hash')").all<{key:string;value:string}>()).results;const values=Object.fromEntries(settings.map(x=>[x.key,x.value]));const derived=await passwordHash(String(b.password||""),values.password_salt||"");if(!user||derived!==values.password_hash)return json({error:"Incorrect name or password."},401);const token=bytesToBase64(crypto.getRandomValues(new Uint8Array(32))).replace(/[^a-zA-Z0-9]/g,"");const hash=await sha256Hex(token);const expires=new Date(Date.now()+30*86400000);await env.DB.prepare("INSERT INTO app_sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(hash,user.id,expires.toISOString(),new Date().toISOString()).run();return new Response(JSON.stringify({ok:true,user}),{headers:{"content-type":"application/json","set-cookie":`mm_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`}});}
 if(url.pathname==="/api/auth/status"&&request.method==="GET"){const user=await currentUser(request,env.DB);return json({authenticated:Boolean(user),user});}
 if(url.pathname==="/api/auth/logout"&&request.method==="POST"){const token=cookieValue(request,"mm_session");if(token)await env.DB.prepare("DELETE FROM app_sessions WHERE token_hash=?").bind(await sha256Hex(token)).run();return new Response(JSON.stringify({ok:true}),{headers:{"content-type":"application/json","set-cookie":"mm_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"}});}
 const authUser=await currentUser(request,env.DB);if(!authUser)return json({error:"Sign in required."},401);
 if(url.pathname==="/api/items"&&request.method==="GET"){const r=await env.DB.prepare("SELECT i.id,i.part_number partNumber,i.name,i.description,i.category,i.qty_needed qtyNeeded,i.qty_on_hand qtyOnHand,i.unit_cost unitCost,i.unit,i.supplier,i.lead_time leadTime,i.bom_level bomLevel,i.notes,COALESCE(p.url,'') purchaseUrl FROM items i LEFT JOIN purchase_links p ON p.item_id=i.id ORDER BY i.name").all();return json(r.results);}
 if(url.pathname==="/api/items"&&request.method==="POST"){const b=await request.json() as Record<string,unknown>;const parsed=validateItem(b);if("error" in parsed)return json(parsed,400);const x=parsed.item;if(await duplicateExists(env.DB,x.partNumber,x.name))return json({error:"An item with this part number and name already exists. Edit the existing item instead."},409);const result=await env.DB.prepare("INSERT INTO items(part_number,name,description,category,qty_needed,qty_on_hand,unit_cost,unit,supplier,lead_time,bom_level,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(x.partNumber,x.name,x.description,x.category,x.qtyNeeded,x.qtyOnHand,x.unitCost,x.unit,x.supplier,x.leadTime,x.bomLevel,x.notes).run();const id=Number(result.meta.last_row_id);const statements=[];if(x.purchaseUrl)statements.push(env.DB.prepare("INSERT INTO purchase_links(item_id,url,updated_at) VALUES(?,?,?)").bind(id,x.purchaseUrl,new Date().toISOString()));if(x.unitCost!==null)statements.push(env.DB.prepare("INSERT INTO price_history(item_id,old_price,new_price,reason,changed_by,created_at) VALUES(?,?,?,?,?,?)").bind(id,null,x.unitCost,String(b.priceChangeReason||"Initial price"),authUser.name,new Date().toISOString()));if(statements.length)await env.DB.batch(statements);return json({ok:true,id},201);}
 const itemMatch=url.pathname.match(/^\/api\/items\/(\d+)$/);if(itemMatch&&request.method==="PUT"){const id=Number(itemMatch[1]);const b=await request.json() as Record<string,unknown>;const parsed=validateItem(b);if("error" in parsed)return json(parsed,400);const x=parsed.item;if(await duplicateExists(env.DB,x.partNumber,x.name,id))return json({error:"Another item with this part number and name already exists."},409);const previous=await env.DB.prepare("SELECT unit_cost unitCost FROM items WHERE id=?").bind(id).first<{unitCost:number|null}>();if(!previous)return json({error:"Item not found"},404);const priceChanged=previous.unitCost!==x.unitCost;const reason=String(b.priceChangeReason||"").trim();if(priceChanged&&!reason)return json({error:"Enter a reason for the price change."},400);const statements=[env.DB.prepare("UPDATE items SET part_number=?,name=?,description=?,category=?,qty_needed=?,qty_on_hand=?,unit_cost=?,unit=?,supplier=?,lead_time=?,bom_level=?,notes=? WHERE id=?").bind(x.partNumber,x.name,x.description,x.category,x.qtyNeeded,x.qtyOnHand,x.unitCost,x.unit,x.supplier,x.leadTime,x.bomLevel,x.notes,id),x.purchaseUrl?env.DB.prepare("INSERT INTO purchase_links(item_id,url,updated_at) VALUES(?,?,?) ON CONFLICT(item_id) DO UPDATE SET url=excluded.url,updated_at=excluded.updated_at").bind(id,x.purchaseUrl,new Date().toISOString()):env.DB.prepare("DELETE FROM purchase_links WHERE item_id=?").bind(id)];if(priceChanged)statements.push(env.DB.prepare("INSERT INTO price_history(item_id,old_price,new_price,reason,changed_by,created_at) VALUES(?,?,?,?,?,?)").bind(id,previous.unitCost,x.unitCost,reason,authUser.name,new Date().toISOString()));await env.DB.batch(statements);return json({ok:true});}
 if(itemMatch&&request.method==="DELETE"){const id=Number(itemMatch[1]);const files=(await env.DB.prepare("SELECT storage_key storageKey FROM print_files WHERE item_id=?").bind(id).all<{storageKey:string}>()).results;await Promise.all(files.map(file=>env.FILES.delete(file.storageKey)));await env.DB.batch([env.DB.prepare("DELETE FROM print_files WHERE item_id=?").bind(id),env.DB.prepare("DELETE FROM purchase_links WHERE item_id=?").bind(id),env.DB.prepare("DELETE FROM transactions WHERE item_id=?").bind(id),env.DB.prepare("DELETE FROM price_history WHERE item_id=?").bind(id),env.DB.prepare("DELETE FROM items WHERE id=?").bind(id)]);return json({ok:true});}
 const linkMatch=url.pathname.match(/^\/api\/items\/(\d+)\/purchase-link$/);if(linkMatch&&request.method==="PUT"){const itemId=Number(linkMatch[1]);const b=await request.json() as {url?:string};const value=(b.url||"").trim();if(value){try{const parsed=new URL(value);if(!["http:","https:"].includes(parsed.protocol))throw new Error();}catch{return json({error:"Enter a valid http or https purchase link."},400);}await env.DB.prepare("INSERT INTO purchase_links(item_id,url,updated_at) VALUES(?,?,?) ON CONFLICT(item_id) DO UPDATE SET url=excluded.url,updated_at=excluded.updated_at").bind(itemId,value,new Date().toISOString()).run();}else await env.DB.prepare("DELETE FROM purchase_links WHERE item_id=?").bind(itemId).run();return json({ok:true,url:value});}
 const priceHistoryMatch=url.pathname.match(/^\/api\/items\/(\d+)\/price-history$/);if(priceHistoryMatch&&request.method==="GET"){const r=await env.DB.prepare("SELECT id,old_price oldPrice,new_price newPrice,reason,changed_by changedBy,created_at createdAt FROM price_history WHERE item_id=? ORDER BY created_at,id").bind(Number(priceHistoryMatch[1])).all();return json(r.results);}
 const printFilesMatch=url.pathname.match(/^\/api\/items\/(\d+)\/print-files$/);if(printFilesMatch){const itemId=Number(printFilesMatch[1]);const item=await env.DB.prepare("SELECT category FROM items WHERE id=?").bind(itemId).first<{category:string}>();if(!item)return json({error:"Item not found"},404);if(item.category.toLowerCase()!=="3d print")return json({error:"File storage is available for 3D Print items."},400);if(request.method==="GET"){const r=await env.DB.prepare("SELECT id,version,file_name fileName,content_type contentType,size_bytes sizeBytes,notes,created_at createdAt FROM print_files WHERE item_id=? ORDER BY created_at DESC,id DESC").bind(itemId).all();return json(r.results);}if(request.method==="POST"){const form=await request.formData();const file=form.get("file");const version=String(form.get("version")||"").trim();const notes=String(form.get("notes")||"").trim();if(!(file instanceof File)||!file.size||!version)return json({error:"Choose a file and enter a version."},400);if(file.size>500*1024*1024)return json({error:"Files must be 500 MB or smaller."},413);const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-");const key=`prints/${itemId}/${crypto.randomUUID()}-${safeName}`;await env.FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type||"application/octet-stream"}});try{const result=await env.DB.prepare("INSERT INTO print_files(item_id,version,file_name,storage_key,content_type,size_bytes,notes,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(itemId,version,file.name,key,file.type||"application/octet-stream",file.size,notes,new Date().toISOString()).run();return json({ok:true,id:Number(result.meta.last_row_id)},201);}catch(error){await env.FILES.delete(key);throw error;}}}
 const printFileMatch=url.pathname.match(/^\/api\/print-files\/(\d+)(\/download)?$/);if(printFileMatch){const id=Number(printFileMatch[1]);const entry=await env.DB.prepare("SELECT storage_key storageKey,file_name fileName,content_type contentType FROM print_files WHERE id=?").bind(id).first<{storageKey:string;fileName:string;contentType:string}>();if(!entry)return json({error:"File not found"},404);if(printFileMatch[2]&&request.method==="GET"){const object=await env.FILES.get(entry.storageKey);if(!object)return json({error:"Stored file not found"},404);const name=entry.fileName.replace(/[\r\n\"]/g,"_");return new Response(object.body,{headers:{"content-type":entry.contentType,"content-length":String(object.size),"content-disposition":`attachment; filename="${name}"`}});}if(!printFileMatch[2]&&request.method==="DELETE"){await env.FILES.delete(entry.storageKey);await env.DB.prepare("DELETE FROM print_files WHERE id=?").bind(id).run();return json({ok:true});}}
 if(url.pathname==="/api/chairs"&&request.method==="GET"){const chairs=(await env.DB.prepare("SELECT id,name,chair_color chairColor,remote_color remoteColor,notes,created_at createdAt FROM chairs ORDER BY id DESC").all()).results;const parts=(await env.DB.prepare("SELECT cp.chair_id chairId,cp.item_id itemId,cp.quantity,cp.status,cp.notes,cp.updated_by updatedBy,cp.updated_at updatedAt FROM chair_parts cp ORDER BY cp.chair_id,cp.item_id").all()).results;const assets=(await env.DB.prepare("SELECT id,chair_id chairId,type,part_id partId,status,updated_at updatedAt,updated_by updatedBy,notes FROM chair_assets ORDER BY chair_id,type").all()).results;return json({chairs,parts,assets});}
 if(url.pathname==="/api/chairs"&&request.method==="POST"){const b=await request.json() as {name?:string;chairColor?:string;remoteColor?:string;notes?:string};const name=String(b.name||"").trim().toUpperCase();if(!name)return json({error:"Enter a chair ID."},400);try{const result=await env.DB.prepare("INSERT INTO chairs(name,chair_color,remote_color,notes,created_at) VALUES(?,?,?,?,?)").bind(name,b.chairColor||"#3274bb",b.remoteColor||"#14161e",b.notes||"",new Date().toISOString()).run();return json({ok:true,id:Number(result.meta.last_row_id)},201);}catch{return json({error:"That chair ID already exists."},409);}}
 const chairMatch=url.pathname.match(/^\/api\/chairs\/(\d+)$/);if(chairMatch&&request.method==="PUT"){const id=Number(chairMatch[1]),b=await request.json() as {name?:string;chairColor?:string;remoteColor?:string;notes?:string};const name=String(b.name||"").trim().toUpperCase();if(!name)return json({error:"Enter a chair ID."},400);await env.DB.prepare("UPDATE chairs SET name=?,chair_color=?,remote_color=?,notes=? WHERE id=?").bind(name,b.chairColor||"#3274bb",b.remoteColor||"#14161e",b.notes||"",id).run();return json({ok:true});}
 if(chairMatch&&request.method==="DELETE"){const id=Number(chairMatch[1]);const chair=await env.DB.prepare("SELECT name FROM chairs WHERE id=?").bind(id).first<{name:string}>();if(!chair)return json({error:"Chair not found."},404);const parts=(await env.DB.prepare("SELECT item_id itemId,quantity FROM chair_parts WHERE chair_id=? AND quantity>0").bind(id).all<{itemId:number;quantity:number}>()).results;const now=new Date().toISOString(),statements=[];for(const p of parts){statements.push(env.DB.prepare("UPDATE items SET qty_on_hand=qty_on_hand+? WHERE id=?").bind(p.quantity,p.itemId));statements.push(env.DB.prepare("INSERT INTO transactions(item_id,kind,quantity,reference,note,created_at) VALUES(?,?,?,?,?,?)").bind(p.itemId,"receive",p.quantity,chair.name,"Returned when chair was deleted",now));}statements.push(env.DB.prepare("DELETE FROM chair_assets WHERE chair_id=?").bind(id),env.DB.prepare("DELETE FROM chair_parts WHERE chair_id=?").bind(id),env.DB.prepare("DELETE FROM chairs WHERE id=?").bind(id));await env.DB.batch(statements);return json({ok:true});}
 const chairPartMatch=url.pathname.match(/^\/api\/chairs\/(\d+)\/parts\/(\d+)$/);if(chairPartMatch&&request.method==="PUT"){const chairId=Number(chairPartMatch[1]),itemId=Number(chairPartMatch[2]),b=await request.json() as {quantity?:number;status?:string;notes?:string};const quantity=Number(b.quantity);if(!Number.isFinite(quantity)||quantity<0)return json({error:"Enter a valid installed quantity."},400);const chair=await env.DB.prepare("SELECT name FROM chairs WHERE id=?").bind(chairId).first<{name:string}>(),item=await env.DB.prepare("SELECT name,qty_on_hand stock FROM items WHERE id=?").bind(itemId).first<{name:string;stock:number}>();if(!chair||!item)return json({error:"Chair or part not found."},404);const prior=await env.DB.prepare("SELECT quantity FROM chair_parts WHERE chair_id=? AND item_id=?").bind(chairId,itemId).first<{quantity:number}>();const old=prior?.quantity||0,delta=quantity-old;if(delta>item.stock)return json({error:`Only ${item.stock} available in inventory.`},409);const now=new Date().toISOString(),kind=delta>0?"use":"receive",amount=Math.abs(delta);const statements=[env.DB.prepare("INSERT INTO chair_parts(chair_id,item_id,quantity,status,notes,updated_by,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(chair_id,item_id) DO UPDATE SET quantity=excluded.quantity,status=excluded.status,notes=excluded.notes,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(chairId,itemId,quantity,b.status||"Installed",b.notes||"",authUser.name,now),env.DB.prepare("UPDATE items SET qty_on_hand=qty_on_hand-? WHERE id=?").bind(delta,itemId)];if(amount>0)statements.push(env.DB.prepare("INSERT INTO transactions(item_id,kind,quantity,reference,note,created_at) VALUES(?,?,?,?,?,?)").bind(itemId,kind,amount,chair.name,delta>0?"Installed on chair":"Returned from chair",now));await env.DB.batch(statements);return json({ok:true});}
 if(url.pathname==="/api/transactions"&&request.method==="GET"){const r=await env.DB.prepare("SELECT t.id,t.item_id itemId,i.name itemName,t.kind,t.quantity,t.reference,t.note,t.created_at createdAt FROM transactions t JOIN items i ON i.id=t.item_id ORDER BY t.id DESC LIMIT 200").all();return json(r.results);}
 if(url.pathname==="/api/transactions"&&request.method==="POST"){const b=await request.json() as {itemId:number;kind:string;quantity:number;reference?:string;note?:string};if(!b.itemId||!["receive","use","adjust"].includes(b.kind)||!Number.isFinite(b.quantity)||b.quantity<0)return json({error:"Invalid transaction"},400);const item=await env.DB.prepare("SELECT qty_on_hand q FROM items WHERE id=?").bind(b.itemId).first<{q:number}>();if(!item)return json({error:"Item not found"},404);const next=b.kind==="receive"?item.q+b.quantity:b.kind==="use"?item.q-b.quantity:b.quantity;if(next<0)return json({error:"Not enough stock"},409);await env.DB.batch([env.DB.prepare("UPDATE items SET qty_on_hand=? WHERE id=?").bind(next,b.itemId),env.DB.prepare("INSERT INTO transactions(item_id,kind,quantity,reference,note,created_at) VALUES(?,?,?,?,?,?)").bind(b.itemId,b.kind,b.quantity,b.reference||"",b.note||"",new Date().toISOString())]);return json({ok:true,qtyOnHand:next},201);}
 if(url.pathname==="/api/new-chair"&&request.method==="POST"){const rows=(await env.DB.prepare("SELECT id,name,qty_needed needed,qty_on_hand available FROM items WHERE qty_needed>0 AND LOWER(category)<>'battery' AND LOWER(name) NOT LIKE '%battery%' ORDER BY id").all<{id:number;name:string;needed:number;available:number}>()).results;const short=rows.filter(i=>i.available<i.needed);if(short.length)return json({error:`Cannot build a chair. Short on: ${short.map(i=>i.name).join(", ")}`},409);const now=new Date().toISOString();const result=await env.DB.prepare("INSERT INTO chairs(name,chair_color,remote_color,notes,created_at) VALUES(?,?,?,?,?)").bind(`PENDING-${crypto.randomUUID()}`,"#3274bb","#14161e","Created with New Chair",now).run();const chairId=Number(result.meta.last_row_id),chairName=`CHAIR-${String(chairId).padStart(3,"0")}`;await env.DB.prepare("UPDATE chairs SET name=? WHERE id=?").bind(chairName,chairId).run();const ref=`New Chair • ${chairName}`,statements=[];for(const i of rows){statements.push(env.DB.prepare("UPDATE items SET qty_on_hand=qty_on_hand-? WHERE id=?").bind(i.needed,i.id));statements.push(env.DB.prepare("INSERT INTO transactions(item_id,kind,quantity,reference,note,created_at) VALUES(?,?,?,?,?,?)").bind(i.id,"use",i.needed,ref,"Installed on tracked chair (batteries excluded)",now));statements.push(env.DB.prepare("INSERT INTO chair_parts(chair_id,item_id,quantity,status,notes,updated_by,updated_at) VALUES(?,?,?,?,?,?,?)").bind(chairId,i.id,i.needed,"Installed","",authUser.name,now));}await env.DB.batch(statements);return json({ok:true,itemsUsed:rows.length,batteriesExcluded:true,chairId,chairName},201);}
 if(url.pathname==="/api/undo"&&request.method==="POST"){const last=await env.DB.prepare("SELECT id,item_id itemId,kind,quantity,reference FROM transactions ORDER BY id DESC LIMIT 1").first<{id:number;itemId:number;kind:string;quantity:number;reference:string}>();if(!last)return json({error:"There is no inventory action to undo."},404);if(last.kind==="adjust")return json({error:"Stock corrections cannot be undone; enter a new correction instead."},409);const isChair=last.reference.startsWith("New Chair •"),group=isChair?(await env.DB.prepare("SELECT id,item_id itemId,kind,quantity FROM transactions WHERE reference=? ORDER BY id").bind(last.reference).all<{id:number;itemId:number;kind:string;quantity:number}>()).results:[last];const statements=[];for(const t of group){const delta=t.kind==="receive"?-t.quantity:t.quantity;statements.push(env.DB.prepare("UPDATE items SET qty_on_hand=qty_on_hand+? WHERE id=?").bind(delta,t.itemId));statements.push(env.DB.prepare("DELETE FROM transactions WHERE id=?").bind(t.id));}if(isChair){const name=last.reference.slice("New Chair •".length).trim(),chair=await env.DB.prepare("SELECT id FROM chairs WHERE name=?").bind(name).first<{id:number}>();if(chair)statements.push(env.DB.prepare("DELETE FROM chair_parts WHERE chair_id=?").bind(chair.id),env.DB.prepare("DELETE FROM chairs WHERE id=?").bind(chair.id));}await env.DB.batch(statements);return json({ok:true,message:group.length>1?"The latest new-chair build was undone.":"The latest inventory action was undone."});}
 if(url.pathname==="/api/deduplicate"&&request.method==="POST"){const rows=(await env.DB.prepare("SELECT id,part_number partNumber,name,description,qty_needed qtyNeeded,qty_on_hand qtyOnHand,unit_cost unitCost,unit,supplier,lead_time leadTime,bom_level bomLevel,notes FROM items ORDER BY id").all<Record<string,unknown>>()).results;const groups=new Map<string,Record<string,unknown>[]>();for(const row of rows){const key=`${String(row.partNumber).trim().toLowerCase()}|${String(row.name).trim().toLowerCase()}`;groups.set(key,[...(groups.get(key)||[]),row]);}let removed=0;for(const group of groups.values()){if(group.length<2)continue;const keeper=group[0];for(const duplicate of group.slice(1)){const comparable=["partNumber","name","description","qtyNeeded","qtyOnHand","unitCost","unit","supplier","leadTime","bomLevel","notes"];if(!comparable.every(k=>String(keeper[k]??"").trim().toLowerCase()===String(duplicate[k]??"").trim().toLowerCase()))continue;const keepId=Number(keeper.id),duplicateId=Number(duplicate.id);await env.DB.batch([env.DB.prepare("UPDATE transactions SET item_id=? WHERE item_id=?").bind(keepId,duplicateId),env.DB.prepare("INSERT INTO purchase_links(item_id,url,updated_at) SELECT ?,url,updated_at FROM purchase_links WHERE item_id=? ON CONFLICT(item_id) DO NOTHING").bind(keepId,duplicateId),env.DB.prepare("DELETE FROM purchase_links WHERE item_id=?").bind(duplicateId),env.DB.prepare("DELETE FROM items WHERE id=?").bind(duplicateId)]);removed++;}}return json({ok:true,removed});}
 if(url.pathname==="/api/chair-appearance"&&request.method==="GET"){const r=await env.DB.prepare("SELECT chair_id chairId,chair_color chairColor,remote_color remoteColor,wheel_position wheelPosition FROM chair_appearance").all();return json(r.results);}
 const appearanceMatch=url.pathname.match(/^\/api\/chairs\/(\d+)\/appearance$/);if(appearanceMatch&&request.method==="PUT"){const chairId=Number(appearanceMatch[1]),b=await request.json() as {chairColor?:string;remoteColor?:string;wheelPosition?:string};await env.DB.prepare("INSERT INTO chair_appearance(chair_id,chair_color,remote_color,wheel_position) VALUES(?,?,?,?) ON CONFLICT(chair_id) DO UPDATE SET chair_color=excluded.chair_color,remote_color=excluded.remote_color,wheel_position=excluded.wheel_position").bind(chairId,b.chairColor||"#3274bb",b.remoteColor||"#14161e",b.wheelPosition==="F"?"F":"M").run();return json({ok:true});}
 const chairModelMatch=url.pathname.match(/^\/api\/chairs\/(\d+)\/model(\/meta)?$/);if(chairModelMatch){const chairId=Number(chairModelMatch[1]);if(chairModelMatch[2]&&request.method==="GET"){const row=await env.DB.prepare("SELECT file_name fileName,size_bytes sizeBytes,uploaded_by uploadedBy,created_at createdAt FROM chair_models WHERE chair_id=?").bind(chairId).first();return row?json(row):json({error:"No model uploaded."},404);}if(!chairModelMatch[2]&&request.method==="GET"){const row=await env.DB.prepare("SELECT storage_key storageKey,file_name fileName,content_type contentType FROM chair_models WHERE chair_id=?").bind(chairId).first<{storageKey:string;fileName:string;contentType:string}>();if(!row)return json({error:"No model uploaded."},404);const object=await env.FILES.get(row.storageKey);if(!object)return json({error:"Stored model not found."},404);return new Response(object.body,{headers:{"content-type":row.contentType,"content-length":String(object.size),"cache-control":"private, max-age=300"}});}if(!chairModelMatch[2]&&request.method==="POST"){const form=await request.formData(),file=form.get("file");if(!(file instanceof File)||!file.size)return json({error:"Choose a GLB model file."},400);if(!file.name.toLowerCase().endsWith(".glb"))return json({error:"Please export the chair assembly as a .glb file."},400);if(file.size>500*1024*1024)return json({error:"The model must be 500 MB or smaller."},413);const existing=await env.DB.prepare("SELECT storage_key storageKey FROM chair_models WHERE chair_id=?").bind(chairId).first<{storageKey:string}>();const key=`chair-models/${chairId}/${crypto.randomUUID()}.glb`;await env.FILES.put(key,file.stream(),{httpMetadata:{contentType:"model/gltf-binary"}});await env.DB.prepare("INSERT INTO chair_models(chair_id,file_name,storage_key,content_type,size_bytes,uploaded_by,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(chair_id) DO UPDATE SET file_name=excluded.file_name,storage_key=excluded.storage_key,content_type=excluded.content_type,size_bytes=excluded.size_bytes,uploaded_by=excluded.uploaded_by,created_at=excluded.created_at").bind(chairId,file.name,key,"model/gltf-binary",file.size,authUser.name,new Date().toISOString()).run();if(existing)await env.FILES.delete(existing.storageKey);return json({ok:true},201);}if(!chairModelMatch[2]&&request.method==="DELETE"){const row=await env.DB.prepare("SELECT storage_key storageKey FROM chair_models WHERE chair_id=?").bind(chairId).first<{storageKey:string}>();if(row)await env.FILES.delete(row.storageKey);await env.DB.prepare("DELETE FROM chair_models WHERE chair_id=?").bind(chairId).run();return json({ok:true});}}
 const itemPriceMatch=url.pathname.match(/^\/api\/items\/(\d+)\/price$/);if(itemPriceMatch&&request.method==="PUT"){const itemId=Number(itemPriceMatch[1]),b=await request.json() as {unitCost?:number|null;reason?:string};const unitCost=b.unitCost===null?null:Number(b.unitCost);if(unitCost!==null&&(!Number.isFinite(unitCost)||unitCost<0))return json({error:"Enter a valid non-negative price."},400);const previous=await env.DB.prepare("SELECT unit_cost unitCost FROM items WHERE id=?").bind(itemId).first<{unitCost:number|null}>();if(!previous)return json({error:"Item not found."},404);if(previous.unitCost===unitCost)return json({ok:true,unchanged:true});const reason=String(b.reason||"Updated in Chair Cost Breakdown").trim()||"Updated in Chair Cost Breakdown",now=new Date().toISOString();await env.DB.batch([env.DB.prepare("UPDATE items SET unit_cost=? WHERE id=?").bind(unitCost,itemId),env.DB.prepare("INSERT INTO price_history(item_id,old_price,new_price,reason,changed_by,created_at) VALUES(?,?,?,?,?,?)").bind(itemId,previous.unitCost,unitCost,reason,authUser.name,now)]);return json({ok:true});}
 const dataSheetsMatch=url.pathname.match(/^\/api\/items\/(\d+)\/data-sheets$/);if(dataSheetsMatch){const itemId=Number(dataSheetsMatch[1]);const item=await env.DB.prepare("SELECT category FROM items WHERE id=?").bind(itemId).first<{category:string}>();if(!item)return json({error:"Item not found."},404);if(item.category.trim().toLowerCase()==="3d print")return json({error:"3D Print items use the 3D Files area."},400);if(request.method==="GET"){const r=await env.DB.prepare("SELECT id,version,file_name fileName,external_url externalUrl,content_type contentType,size_bytes sizeBytes,notes,created_at createdAt FROM data_sheets WHERE item_id=? ORDER BY created_at DESC,id DESC").bind(itemId).all();return json(r.results);}if(request.method==="POST"){const form=await request.formData(),file=form.get("file"),version=String(form.get("version")||"").trim(),notes=String(form.get("notes")||"").trim();if(!(file instanceof File)||!file.size||!version)return json({error:"Choose a document and enter a revision."},400);if(file.size>100*1024*1024)return json({error:"Data sheets must be 100 MB or smaller."},413);const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-"),key=`data-sheets/${itemId}/${crypto.randomUUID()}-${safe}`;await env.FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type||"application/octet-stream"}});const result=await env.DB.prepare("INSERT INTO data_sheets(item_id,version,file_name,storage_key,external_url,content_type,size_bytes,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(itemId,version,file.name,key,"",file.type||"application/octet-stream",file.size,notes,new Date().toISOString()).run();return json({ok:true,id:Number(result.meta.last_row_id)},201);}}
 const dataSheetMatch=url.pathname.match(/^\/api\/data-sheets\/(\d+)(\/download)?$/);if(dataSheetMatch){const id=Number(dataSheetMatch[1]),entry=await env.DB.prepare("SELECT storage_key storageKey,external_url externalUrl,file_name fileName,content_type contentType FROM data_sheets WHERE id=?").bind(id).first<{storageKey:string|null;externalUrl:string;fileName:string;contentType:string}>();if(!entry)return json({error:"Data sheet not found."},404);if(dataSheetMatch[2]&&request.method==="GET"){if(entry.externalUrl)return Response.redirect(entry.externalUrl,302);if(!entry.storageKey)return json({error:"Stored document not found."},404);const object=await env.FILES.get(entry.storageKey);if(!object)return json({error:"Stored document not found."},404);const name=entry.fileName.replace(/[\r\n\"]/g,"_");return new Response(object.body,{headers:{"content-type":entry.contentType,"content-length":String(object.size),"content-disposition":`inline; filename="${name}"`}});}if(!dataSheetMatch[2]&&request.method==="DELETE"){if(entry.storageKey)await env.FILES.delete(entry.storageKey);await env.DB.prepare("DELETE FROM data_sheets WHERE id=?").bind(id).run();return json({ok:true});}}
 if(url.pathname==="/api/hardware-assets"&&request.method==="GET"){
  const assets=(await env.DB.prepare("SELECT h.id,h.asset_tag assetTag,h.kind,h.model,h.serial_number serialNumber,h.chair_id chairId,c.name chairName,h.notes,h.updated_at updatedAt,h.updated_by updatedBy,(SELECT flashed_at FROM hardware_flashes f WHERE f.asset_id=h.id ORDER BY flashed_at DESC,id DESC LIMIT 1) lastFlashedAt,(SELECT image_name FROM hardware_flashes f WHERE f.asset_id=h.id ORDER BY flashed_at DESC,id DESC LIMIT 1) lastImageName,(SELECT version FROM hardware_flashes f WHERE f.asset_id=h.id ORDER BY flashed_at DESC,id DESC LIMIT 1) lastVersion,(SELECT flashed_by FROM hardware_flashes f WHERE f.asset_id=h.id ORDER BY flashed_at DESC,id DESC LIMIT 1) lastFlashedBy FROM hardware_assets h LEFT JOIN chairs c ON c.id=h.chair_id ORDER BY h.kind,h.asset_tag").all()).results;
  const chairs=(await env.DB.prepare("SELECT id,name FROM chairs ORDER BY name").all()).results;
  const flashes=(await env.DB.prepare("SELECT id,asset_id assetId,flashed_at flashedAt,image_name imageName,version,notes,flashed_by flashedBy,created_at createdAt FROM hardware_flashes ORDER BY flashed_at DESC,id DESC").all()).results;
  return json({assets,chairs,flashes});
 }
 if(url.pathname==="/api/hardware-assets"&&request.method==="POST"){
  const b=await request.json() as Record<string,unknown>,assetTag=String(b.assetTag||"").trim().toUpperCase(),kind=String(b.kind||"");const chairId=b.chairId?Number(b.chairId):null;
  if(!assetTag||!["Jetson","PCB"].includes(kind))return json({error:"Enter an asset tag and choose Jetson or PCB."},400);
  if(chairId&&!await env.DB.prepare("SELECT id FROM chairs WHERE id=?").bind(chairId).first())return json({error:"Chair not found."},404);
  const now=new Date().toISOString();try{const result=await env.DB.prepare("INSERT INTO hardware_assets(asset_tag,kind,model,serial_number,chair_id,notes,created_at,updated_at,updated_by) VALUES(?,?,?,?,?,?,?,?,?)").bind(assetTag,kind,String(b.model||"").trim(),String(b.serialNumber||"").trim(),chairId,String(b.notes||"").trim(),now,now,authUser.name).run();if(chairId)await env.DB.prepare("INSERT OR IGNORE INTO chair_assets(chair_id,type,part_id,status,updated_at,updated_by,notes) VALUES(?,?,?,?,?,?,?)").bind(chairId,kind==="Jetson"?"Jetson":"PCB",assetTag,"Installed",now,authUser.name,String(b.notes||"").trim()).run();return json({ok:true,id:Number(result.meta.last_row_id)},201);}catch{return json({error:"That asset tag already exists."},409);}
 }
 const hardwareMatch=url.pathname.match(/^\/api\/hardware-assets\/(\d+)$/);
 if(hardwareMatch&&request.method==="PUT"){
  const id=Number(hardwareMatch[1]),prior=await env.DB.prepare("SELECT asset_tag assetTag,kind FROM hardware_assets WHERE id=?").bind(id).first<{assetTag:string;kind:string}>();if(!prior)return json({error:"Board not found."},404);
  const b=await request.json() as Record<string,unknown>,assetTag=String(b.assetTag||"").trim().toUpperCase(),kind=String(b.kind||""),chairId=b.chairId?Number(b.chairId):null;if(!assetTag||!["Jetson","PCB"].includes(kind))return json({error:"Enter an asset tag and choose Jetson or PCB."},400);if(chairId&&!await env.DB.prepare("SELECT id FROM chairs WHERE id=?").bind(chairId).first())return json({error:"Chair not found."},404);
  const now=new Date().toISOString(),notes=String(b.notes||"").trim();try{const statements=[env.DB.prepare("UPDATE hardware_assets SET asset_tag=?,kind=?,model=?,serial_number=?,chair_id=?,notes=?,updated_at=?,updated_by=? WHERE id=?").bind(assetTag,kind,String(b.model||"").trim(),String(b.serialNumber||"").trim(),chairId,notes,now,authUser.name,id),env.DB.prepare("DELETE FROM chair_assets WHERE part_id IN (?,?) AND (type='PCB' OR LOWER(type) LIKE '%jetson%')").bind(prior.assetTag,assetTag)];if(chairId)statements.push(env.DB.prepare("INSERT INTO chair_assets(chair_id,type,part_id,status,updated_at,updated_by,notes) VALUES(?,?,?,?,?,?,?)").bind(chairId,kind==="Jetson"?"Jetson":"PCB",assetTag,"Installed",now,authUser.name,notes));await env.DB.batch(statements);return json({ok:true});}catch{return json({error:"That asset tag already exists."},409);}
 }
 if(hardwareMatch&&request.method==="DELETE"){
  const id=Number(hardwareMatch[1]),prior=await env.DB.prepare("SELECT asset_tag assetTag FROM hardware_assets WHERE id=?").bind(id).first<{assetTag:string}>();if(!prior)return json({error:"Board not found."},404);await env.DB.batch([env.DB.prepare("DELETE FROM chair_assets WHERE part_id=? AND (type='PCB' OR LOWER(type) LIKE '%jetson%')").bind(prior.assetTag),env.DB.prepare("DELETE FROM hardware_flashes WHERE asset_id=?").bind(id),env.DB.prepare("DELETE FROM hardware_assets WHERE id=?").bind(id)]);return json({ok:true});
 }
 const flashMatch=url.pathname.match(/^\/api\/hardware-assets\/(\d+)\/flashes$/);
 if(flashMatch&&request.method==="POST"){
  const assetId=Number(flashMatch[1]);if(!await env.DB.prepare("SELECT id FROM hardware_assets WHERE id=?").bind(assetId).first())return json({error:"Board not found."},404);const b=await request.json() as Record<string,unknown>,imageName=String(b.imageName||"").trim(),dateValue=String(b.flashedAt||"").trim();if(!imageName||!dateValue||Number.isNaN(Date.parse(dateValue)))return json({error:"Enter the flash date and software or image name."},400);const flashedAt=new Date(dateValue).toISOString(),now=new Date().toISOString();await env.DB.batch([env.DB.prepare("INSERT INTO hardware_flashes(asset_id,flashed_at,image_name,version,notes,flashed_by,created_at) VALUES(?,?,?,?,?,?,?)").bind(assetId,flashedAt,imageName,String(b.version||"").trim(),String(b.notes||"").trim(),authUser.name,now),env.DB.prepare("UPDATE hardware_assets SET updated_at=?,updated_by=? WHERE id=?").bind(now,authUser.name,assetId)]);return json({ok:true},201);
 }
 return json({error:"Not found"},404);
}

function validateItem(b:Record<string,unknown>){const name=String(b.name||"").trim();const category=String(b.category||"Other").trim()||"Other";const qtyNeeded=Number(b.qtyNeeded);const qtyOnHand=Number(b.qtyOnHand);const unit=String(b.unit||"").trim();const unitCost=b.unitCost===null||b.unitCost===""?null:Number(b.unitCost);const bomLevel=b.bomLevel===null||b.bomLevel===""?null:Number(b.bomLevel);const purchaseUrl=String(b.purchaseUrl||"").trim();if(!name||!unit||!Number.isFinite(qtyNeeded)||qtyNeeded<=0||!Number.isFinite(qtyOnHand)||qtyOnHand<0||unitCost!==null&&(!Number.isFinite(unitCost)||unitCost<0)||bomLevel!==null&&!Number.isFinite(bomLevel))return {error:"Enter a name, unit, positive quantity per chair, and valid non-negative values."};if(purchaseUrl){try{const u=new URL(purchaseUrl);if(!["http:","https:"].includes(u.protocol))throw new Error();}catch{return {error:"Enter a valid http or https purchase link."};}}return {item:{partNumber:String(b.partNumber||"").trim(),name,description:String(b.description||"").trim(),category,qtyNeeded,qtyOnHand,unitCost,unit,supplier:String(b.supplier||"").trim(),leadTime:String(b.leadTime||"").trim(),bomLevel,notes:String(b.notes||"").trim(),purchaseUrl}};}
async function duplicateExists(db:D1Database,partNumber:string,name:string,excludeId=0){const row=await db.prepare("SELECT id FROM items WHERE LOWER(TRIM(part_number))=? AND LOWER(TRIM(name))=? AND id<>? LIMIT 1").bind(partNumber.trim().toLowerCase(),name.trim().toLowerCase(),excludeId).first();return Boolean(row);}

export default worker;
